title: "Milo"

description: "Bootstrap theme for jekyll"
# markdown: kramdown
url: ""
baseurl: "/jekyll-theme-milo"

# The shortname for your Disqus site to enable comments.
disqus: anistark

# Colors
accent_color: "#2d72d9"

plugins:
  - jekyll-paginate
  - jemoji

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/page:num/"

main_toc:
  - title: Home
    url: ""
  - title: About
    url: "about"
  - title: Author
    url: "author"

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
